name: Test d'un workflow Hello World
on:
  - push
jobs:
  premierJob:
    runs-on: ubuntu-latest
    steps:
      - name: Test hello World
        run: echo "hello world"

  testJob:
    runs-on: Ubuntu-20.04
    steps:
      - name: Run tests
        run: python3 all_tests.py